version: '3.8'

services:
  backend:
    build:
      context: ./BACKEND
    ports:
      - "4000:4000"
    env_file:
      - ./BACKEND/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend
    restart: unless-stopped
