name: Deploy TecnoShop (Backend y Frontend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v5
        with:
          context: ./BACKEND
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/back:latest

      - name: Build and push frontend image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front:latest

      - name: Deploy backend and frontend on EC2
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Parar y eliminar contenedor backend si existe
            docker stop back || true
            docker rm back || true
            # Parar y eliminar contenedor frontend si existe
            docker stop front || true
            docker rm front || true

            # Descargar últimas imágenes
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/back:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/front:latest

            # Ejecutar backend
            docker run -d --name back -p 4000:4000 \
              -e OPENWEATHER_API_KEY="${{ secrets.OPENWEATHER_API_KEY }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/back:latest

            # Ejecutar frontend
            docker run -d --name front -p 5173:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/front:latest
