name: Deploy TecnoShop (Backend y Frontend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify Docker Hub secrets
        run: |
          echo "DOCKERHUB_USERNAME is '${{ secrets.DOCKERHUB_USERNAME }}'"
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "ERROR: DOCKERHUB_USERNAME is empty!"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "ERROR: DOCKERHUB_TOKEN is empty!"
            exit 1
          fi
          echo "Secrets OK."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./BACKEND
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/back:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front:latest

      - name: Deploy backend and frontend on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop back || true
            docker rm back || true
            docker stop front || true
            docker rm front || true

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/back:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/front:latest

            docker run -d --name back -p 4000:4000 \
              -e OPENWEATHER_API_KEY="${{ secrets.OPENWEATHER_API_KEY }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/back:latest

            docker run -d --name front -p 5173:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/front:latest
