name: Test DockerHub Secrets

on:
  push:
    main
jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show Docker Hub username
        run: echo "DOCKERHUB_USERNAME is set to '${{ secrets.DOCKERHUB_USERNAME }}'"

      - name: Check Docker Hub token length
        run: |
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is empty!"
            exit 1
          else
            echo "DOCKERHUB_TOKEN length is ${#DOCKERHUB_TOKEN}"
          fi

      - name: Try login to Docker Hub (dry run)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
